export default [
  {
    id: 1,
    name: "DrogoTheBlack",
    rank: "Legend",
    rankImg: "GoldRupee.png",
    points: "1550",
    coverImg: "Legend.png",
    position: "1st",
  },
  ,
  {
    id: 2,
    name: "Tarnished",
    rank: "GrandMaster",
    rankImg: "SilverRupee.png",
    points: "1310",
    coverImg: "Grandmaster.png",
    position: "2nd",
  },
  {
    id: 3,
    name: "Dovahkiin",
    rank: "Master",
    rankImg: "PurpleRupee.png",
    points: "1299",
    coverImg: "Master.png",
    position: "3nd",
  },
  {
    id: 4,
    name: "HeroOfTime",
    rank: "Adept",
    rankImg: "RedRupee.png",
    points: "1110",
    coverImg: "Adept.png",
    position: "4th",
  },
  {
    id: 5,
    name: "Dovahkiin",
    rank: "Apprentice",
    rankImg: "BlueRupee.png",
    points: "980",
    coverImg: "Apprentice.png",
    position: "5th",
  },
  {
    id: 6,
    name: "Caranthir",
    rank: "Explorer",
    rankImg: "GreenRupee.png",
    points: "900",
    coverImg: "Explorer.png",
    position: "3nd",
  },
];
