export default [
  {
    id: 1,
    name: "DrogoTheBlack",
    rank: "Challenger",
    rankImg: "GoldRupee.png",
    points: "1550",
    coverImg: "Drogo.png",
    position: "1st",
  },
  ,
  {
    id: 2,
    name: "Tarnished",
    rank: "GrandMaster",
    rankImg: "PurpleRupee.png",
    points: "1310",
    coverImg: "Tarnished.png",
    position: "2nd",
  },
  {
    id: 3,
    name: "Dovahkiin",
    rank: "Dragonborn",
    rankImg: "PurpleRupee.png",
    points: "1299",
    coverImg: "Dovahkiin.png",
    position: "3nd",
  },
  {
    id: 4,
    name: "HeroOfTime",
    rank: "Legend",
    rankImg: "RedRupee.png",
    points: "1110",
    coverImg: "HeroOfTime.png",
    position: "4th",
  },
  {
    id: 5,
    name: "Dovahkiin",
    rank: "Dragonborn",
    rankImg: "BlueRupee.png",
    points: "980",
    coverImg: "Dovahkiin.png",
    position: "5th",
  },
  {
    id: 6,
    name: "Dovahkiin",
    rank: "Dragonborn",
    rankImg: "BlueRupee.png",
    points: "1299",
    coverImg: "Dovahkiin.png",
    position: "3nd",
  },
];
